- hosts: prod
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: [docker.io]
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable & start Docker
      systemd:
        name: docker
        enabled: yes
        state: started
