apiVersion: v1
kind: Service
metadata:
  name: catbox-clone
  namespace: default
spec:
  selector:
    app: catbox-clone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
