apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catbox-clone
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: catbox-clone
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
