apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catbox-clone-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: catbox-clone
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
