global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'catbox-clone'
    static_configs:
      - targets: ['catbox-clone:8081'] 
