name: CI Development
on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('services/catbox-clone/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        working-directory: services/catbox-clone
        run: go mod tidy
      - name: Run unit tests
        working-directory: services/catbox-clone
        run: go test ./... -v
      - name: Build Docker image
        working-directory: services/catbox-clone
        run: docker build -t catbox-clone:dev .
      - name: Set up Kind
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: catbox-cluster
          config: kind-cluster.yaml
      - name: Load Docker image to Kind
        run: kind load docker-image catbox-clone:dev --name catbox-cluster
      - name: Deploy to Kind
        run: |
          kubectl apply -f deploy/k8s/catbox-deployment.yaml
          kubectl apply -f deploy/k8s/catbox-service.yaml
      - name: Install monitoring
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
      - name: Test service accessibility
        run: |
          kubectl port-forward svc/catbox-clone 8080:80 --namespace default &
          sleep 10
          curl -f http://localhost:8080
          curl -f http://localhost:8080/metrics
