name: CI Development
on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: services/catbox-clone
        run: go mod tidy

      - name: Run unit tests
        working-directory: services/catbox-clone
        run: go test ./... -v

      - name: Build Docker image
        run: docker build -t catbox-clone:dev ./services/catbox-clone

      - name: Set up Kind
        uses: helm/kind-action@v1.10.0
        with:
          clusterName: catbox-cluster

      - name: Load Docker image
        run: kind load docker-image catbox-clone:dev --name catbox-cluster

      - name: Deploy catbox
        run: kubectl apply -f deploy/k8s/

      - name: Install monitoring
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack \
            -f deploy/monitoring/prometheus-values.yaml \
            -n monitoring --create-namespace

      - name: Smoke test
        run: |
          kubectl wait --for=condition=available deployment/catbox-clone --timeout=60s
          kubectl port-forward svc/catbox-clone 8080:80 & sleep 5
          curl -f http://localhost:8080/
          curl -f http://localhost:8080/metrics
